events { worker_connections 1024;
 }

http {
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=register:10m rate=3r/m;
    include /etc/nginx/mime.types;

    upstream orchestrator { server orchestrator:8000; 
    }

    server {
        listen 80;
        server_name app.agdev10.online;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name app.agdev10.online;

        ssl_certificate     /etc/letsencrypt/live/app.agdev10.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/app.agdev10.online/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /health {
            proxy_pass http://orchestrator/health;
        }

        location /api/register {
            limit_req zone=register burst=2 nodelay;
            rewrite ^/api/register$ /register break;
            proxy_pass http://orchestrator;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            limit_req zone=api burst=20 nodelay;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://orchestrator;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }
    }
}